name: Hourly API Call
on:
  schedule:
    - cron: '0 * * * *' # 1時間に1回
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl -s "https://roblox-discovery-hdj5p5k6f-sencat-devs-projects.vercel.app/api/cron"
